### ISSUE TITLE
Publish master to npm?

### ISSUE THREAD

**Issue by tmikeschu** [mswjs/live-storage#7]
Hello! It looks like 0.0.1 is not current with the master branch. I noticed that `getValue` is not a method on a `LiveStorage` instance.

**Comment by kettanaito** [comment]
Hey, @tmikeschu.

I've published the latest state of the repository as the 0.1.0 version.

## Warning

Please note that this library is about to be discontinued. We recommend our users to migrate to the [@mswjs/data](https://github.com/mswjs/data) library that provides data modeling capabilities, querying client, and persistency similar to what the "storage" library provides. 

- [Announcing "data"—data modeling library for testing JavaScript applications](https://dev.to/kettanaito/announcing-mswjs-data-data-modeling-library-for-testing-javascript-applications-3290)

Please strongly consider migrating. Thank you.

**Comment by tmikeschu** [comment]
@kettanaito thanks!
